version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - type: bind
        source: ./
        target: /app
        read_only: true

  production:
    build:
      context: ./
      dockerfile: Dockerfile.production
    container_name: production
    command: npm run test
