version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - type: bind
        source: ./
        target: /app
        read_only: true
    depends_on:
      - db

  production:
    build:
      context: ./
      dockerfile: Dockerfile.production
    container_name: production
    command: npm run test

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=$NODOS_DB_USERNAME
      - POSTGRES_PASSWORD=$NODOS_DB_PASSWORD
